
//article相关
const EDIT_ARTICLE       ='EDIT_ARTICLE'
const ADD_ARTICLE        ='ADD_ARTICLE'
const DELETE_ARTICLE     ='DELETE_ARTICLE'
const SET_ACTIVE_ARTICLE ='SET_ACTIVE_ARTICLE'
const RECEIVE_ARTICLE ='RECEIVE_ARTICLE'
const TOGGLE_FAVORITE ='RECEIVE_ATOGGLE_FAVORITERTICLE' 

export default {
    //article相关
    EDIT_ARTICLE,ADD_ARTICLE,DELETE_ARTICLE,SET_ACTIVE_ARTICLE ,RECEIVE_ARTICLE,TOGGLE_FAVORITE
}